apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ai-model-ingress
  namespace: ai-model-service
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "ai-model-ip"
    networking.gke.io/managed-certificates: "ai-model-cert"
    networking.gke.io/v1beta1.FrontendConfig: "ai-model-frontend-config"
spec:
  rules:
  - host: api.aimodel.example.com
    http:
      paths:
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: backend
            port:
              number: 80
  - host: aimodel.example.com
    http:
      paths:
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: frontend
            port:
              number: 80

---
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: ai-model-frontend-config
  namespace: ai-model-service
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT

---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: ai-model-cert
  namespace: ai-model-service
spec:
  domains:
    - aimodel.example.com
    - api.aimodel.example.com