# .github/workflows/deploy.yml
name: Deploy to GCP

on:
  push:
    branches: [ main ]

env:
  PROJECT_ID: ai-model-service-[YOUR_SUFFIX]
  GKE_CLUSTER: ai-model-cluster
  GKE_ZONE: asia-northeast3-a
  REGISTRY: asia-northeast3-docker.pkg.dev
  BACKEND_IMAGE: asia-northeast3-docker.pkg.dev/ai-model-service-[YOUR_SUFFIX]/ai-model-service/backend
  FRONTEND_IMAGE: asia-northeast3-docker.pkg.dev/ai-model-service-[YOUR_SUFFIX]/ai-model-service/frontend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ env.PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Configure Docker
      run: |
        gcloud auth configure-docker ${{ env.REGISTRY }}

    - name: Build Backend
      run: |
        docker build -t ${{ env.BACKEND_IMAGE }}:${{ github.sha }} ./backend
        docker push ${{ env.BACKEND_IMAGE }}:${{ github.sha }}
        docker tag ${{ env.BACKEND_IMAGE }}:${{ github.sha }} ${{ env.BACKEND_IMAGE }}:latest
        docker push ${{ env.BACKEND_IMAGE }}:latest

    - name: Build Frontend
      run: |
        docker build -t ${{ env.FRONTEND_IMAGE }}:${{ github.sha }} ./frontend
        docker push ${{ env.FRONTEND_IMAGE }}:${{ github.sha }}
        docker tag ${{ env.FRONTEND_IMAGE }}:${{ github.sha }} ${{ env.FRONTEND_IMAGE }}:latest
        docker push ${{ env.FRONTEND_IMAGE }}:latest

    - name: Get GKE credentials
      run: |
        gcloud container clusters get-credentials ${{ env.GKE_CLUSTER }} --zone ${{ env.GKE_ZONE }}

    - name: Deploy to GKE
      run: |
        kubectl apply -f kubernetes/namespace.yaml
        kubectl apply -f kubernetes/secrets.yaml
        kubectl apply -f kubernetes/postgres.yaml
        kubectl apply -f kubernetes/backend.yaml
        kubectl apply -f kubernetes/frontend.yaml
        kubectl apply -f kubernetes/ingress.yaml

    - name: Update deployments
      run: |
        kubectl set image deployment/backend backend=${{ env.BACKEND_IMAGE }}:${{ github.sha }} -n ai-model-service
        kubectl set image deployment/frontend frontend=${{ env.FRONTEND_IMAGE }}:${{ github.sha }} -n ai-model-service